service: celebrity-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DATABASE_URL: "postgresql://admin:SnJMcSDOZklJqDw1tdGebOU3VV3rVdvv@dpg-d1jqqtndiees73ceudfg-a.oregon-postgres.render.com/celebrity"
    GEMINI_API_KEY: "AIzaSyBD_utWk9qja0FuU5daDQsK7Q2OykUFQ60"

  httpApi:
    cors:
      allowedOrigins:
        - https://celebrity-app2.vercel.app
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
  stage: dev

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

package:
  exclude:
    - node_modules/**
    - test/**
    - src/**
    - tsconfig.json

plugins:
  - serverless-offline


build:
  esbuild: false